INSERT INTO HOBBY (ID,DESCRIPTION, NAME) VALUES (2,'Hobby 2 mission ','hobby 2');
INSERT INTO HOBBY (ID,DESCRIPTION, NAME) VALUES (3,'Hobby 3 mission ','hobby 3');
INSERT INTO HOBBY (ID,DESCRIPTION, NAME) VALUES (4,'Hobby 4 mission ','hobby 4');

INSERT INTO HOBBY_INFOENTITY (HOBBYS_ID,LISTPERSON_ID) VALUES (1,1);
INSERT INTO HOBBY_INFOENTITY (HOBBYS_ID,LISTPERSON_ID) VALUES (2,1);
INSERT INTO HOBBY_INFOENTITY (HOBBYS_ID,LISTPERSON_ID) VALUES (3,1);
INSERT INTO HOBBY_INFOENTITY (HOBBYS_ID,LISTPERSON_ID) VALUES (4,1);